-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 10, 2022 at 04:44 PM
-- Server version: 10.4.19-MariaDB
-- PHP Version: 8.0.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `fantasy_pet`
--

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `price` int(11) NOT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`id`, `name`, `price`, `description`, `category`) VALUES
(1, '2in1 Backpack', 65000, 'Gendongan untuk hewan peliharaan yg cocok utk kucing berukuran sedang / anjing kecil<br>Note : tolong perhatikan ukurannya dulu ya, anabulnya diukur dulu ya kk agar menghindari ukuran yg kekecilan / kebesaran<br><br>Ukuran Produk Lingkar Dada&Perut = 44cm, Tinggi Keseluruhan = 40cm<br><br>● Tas Terbuat Dari Bahan Yang Kuat Tidak Mudah Sobek<br>● Tipe/Model Tas Berbentuk Gendongan/Ransel Depan/Belakang<br>● Sangat Cocok Untuk Kucing Dan Anjing<br>● Tali Ransel Dilengkapi Dengan Sabuk Pengaman<br>● Pada Bagian Depan Terdapat Lubang Kaki Dan Tangan Yang Sudah Disesuaikan Untuk Hewan<br>● Tersedia Lubang Untuk Ekor<br>● Bagian Dalam Terdapat Tali Gantung Bisa DiCantolkan Ke Kalung Hewan<br>● Bahan Glosy Dan Waterproof<br>● Mudah Dibersihkan Cukup Di Lap<br>● Ukuran Produk Lingkar Dada&Perut = 44cm, Tinggi Keseluruhan = 36cm', 'Toy / Utility'),
(2, '3in1 Backpack', 98500, '●Tas tempat hewan kucing, anjing, reptil, burung. Model Terbaru 3 in 1 (Bisa selempang, ransel, jinjing).<br>●Jendela utama depan dari bahan karet kuat elastis tidak bisa sobek dicakar hewan.<br>●Ada tempat kantong 2 (samping kanan kiri)<br>●Ada lubang ventilasi mata ayam (samping kanan kiri)<br>●Ada tali pengikat hewan di dalam tasnya.<br>●Bahan tebal tidak penyok<br>●Anti air (waterproof).<br>●Motif cantik dan menarik.<br>●Dimensi Ukuran tas = Panjang 45cm Lebar 28cm Tinggi 30cm.<br>●Jahitan sangat rapi.<br>●Bagian bawah tas ada lapisan multiplek tebal, kuat dan bisa di lepas pasang untuk mempermudah tas dicuci/dibersihkan.', 'Toy / Utility'),
(3, 'Albenworm', 6000, 'Harga di atas adalah harga per tablet.<br><br>Obat cacing Albenworm dari Raid All kini hadir dalam bentuk tablet yang praktis digunakan untuk hewan kesayangan anda.<br><br>Manfaat :<br>Membasmi cacing gilig roundworms, cacing tambang hookworms, cacing pita cestoda, cacing paru, dan cacing babi.<br><br>Aturan pakai :<br>Disuapkan langsung kedalam mulut hewan (menggunakan sepetan atau jika sudah terbiasa, menggunakan jari). Diberikan 2 jam sebelum makan.<br>Infeksi cacing berat diberikan 3 hari berturut - turut dan untuk pencegahan diberikan setiap 2 bulan sekali.<br>Berat hewan < 5 kg : 1/4 tablet<br>Berat badan > 5 kg : 1/2 tablet<br><br>TIDAK DIANJURKAN UNTUK :<br>1. HEWAN YANG SEDANG ATAU AKAN HAMIL<br>2. ANAK KUCING DIBAWAH USIA 3 BULAN.', 'Healthcare'),
(4, 'Armani Shampoo', 33000, '❤️Shampoo Kucing - Armani - Tick And Flea❤️<br>Fragrance: floral blue<br><br>Shampoo yang diformulasikan untuk membunuh kutu, caplak, pinjal, serangga yang mengganggu. Dengan obat anti kutu dengan kadar aman sesuai ijin dokter hewan. Dibuat dengan aroma floral blue yang wangi tahan lama.<br><br>Aman untuk kitten (anak kucing) diatas 6 bulanan ya ka', 'Healthcare'),
(5, 'Ball Toy', 98000, 'Kondisi: Baru<br>Berat: 105 Gram<br>Kategori: Mainan Kucing<br>Etalase: Semua Etalase<br>Warna : Putih<br>Diameter : -+ 6cm<br>Material: ABS Plastic<br>Battery: Built-in Battery (Included)<br><br>100% Brand new and high quality.<br>Ramah lingkungan & tahan terhadap bantingan: bahannya plastik ABS yg ramah lingkungan, tahan gigitan & tahan jatuh.<br><br>Fitur :<br>- USB rechargeable: Mesin yg tahan & kuat, dapat di cas 1.5 - 2 jam, bisa aktif 3-4 jam<br>- BERHENTI OTOMATIS Setelah NYALA SELAMA 10-15MENIT<br>- Membuat kucing berolahraga (sehat bugar)<br>- Disertai LED flash, menarik perhatian kucing<br>- Didesain dapat menghindari rintangan, berputar sentrifugal, secara otomatis berputar ketika bertemu rintangan.<br><br>Packaging Includes:<br>1 xCat toy ball<br>1 xUSB charging cable', 'Toy / Utility'),
(6, 'BODY Big Cat', 35000, 'BODY BIG<br><br><br>Bentuk serbuk<br><br>PENGGEMUK KUCING<br>VITAMIN KOMPLIT<br>+ CALSIUM<br><br>- UNTUK KUCING MULAI USIA 2 BULAN SAMPAI DEWASA<br>- REKOMENDASI DARI DOKTER, , BAIK SEKALI DI GUNAKAN KUCING SEDANG HAMIL, AGAR PERTUMBUHAN BABY KUCING MENJADI LEBIH KUAT<br><br>Cara pakai<br>CAMPUR KAN DI MAKANAN, BISA MAKANAN BASAH ATAU KERING<br>BERIKAN 1/2 SENDOK TEH PER SEKALI TAKARAN MAKAN<br><br>1 HARI BERIKAN 2 X<br>AMAN DI BERIKAN TIAP HARI<br><br><br>CAT FATER POWDER<br>COMPLETE VITAMIN<br>+ CALSIUM<br><br>- FOR AGES 2 MONTH TO ADULT<br>- RECOMMENDATIONS FROM DOCTOR , GOOD AT ALL USING A PREGNANT CAT, IN ORDER TO GROW BABY CAT TO BETTER<br><br>How to use<br>MIX IN FOOD, CAN FOOD WET OR DRY<br>GIVE 1/2 SPOON TEA PER ONCE MEAT DINING<br><br>1 DAY GIVE 2 X<br>SAFE IS GIVEN EVERYDAY', 'Healthcare'),
(7, 'Bolt Kitten', 25000, 'Makanan anak kucing Bolt Salmon Kitten Cat Food<br><br>Bolt Salmon Kitten Cat Food Kibble Half Moon merupakan pakan kucing yang tinggi protein untuk menunjang pertumbuhan kucing kitten, mendukung pembentukan gigi dan tulang, serta mampu meningkatkan fungsi pencernaan. Pakan ini juga baik untuk kesehatan kulit, bulu, dan penglihatan yang tajam.<br><br>Untuk segala jenis kucing dengan usia dibawah 1 tahun<br><br>Komposisi :<br>Tepung Ikan, Tepung Ayam, Jagung, Beras, Kedelai, Tepung Jagung, Minyak Ikan, Minyak Ayam, Ragi,<br>Taurin, Vitamin dan Mineral, Antioksidan.<br><br>Nilai gizi :<br>Protein 30%, lemak 9%, serat 5%, abu 10%, kalsium 1%, fosfor 0.8%, kadar air 10%<br><br>Keunggulan produk :<br>Membuat kulit sehat dan bulu berkilau, mempertajam penglihatan, membantu menjaga kesehatan gigi, mengurangi resiko FLUTD ( penyakit saluran kemih pada kucing ), dan meningkatkan sistem imunitas<br><br>Berat bersih : 1kg', 'Food'),
(8, 'Bolt tuna - 900gr', 19999, 'NETTO 900Gr ya kk<br>(Timbangan menggunakan timbangan digital yg punya sertifikat uji dari badan metrologi Indonesia. Biasa digunakan di Alfa/indomaret dan ekspedisi2 indonesia seperti JNT)<br><br>Ada 2 kemasan, di kirim Random ☺️<br>1. Plastik Bolt<br>2. Plastik Zipper Lock<br>Dengan kemasan zipper lock tebal dan praktis, menjaga kualitas makanan si empuss supaya tetap fresh<br><br>Makanan kering repack merk bolt<br>NETTO: 900gr<br>Bentuk: Ikan<br>Rasa: Tuna<br><br>- Semua produk yang kita jual adalah Original langsung dari pabriknya<br>- Untuk bolt donat, biasanya serbuknya (tidak menutupi kemungkinan juga bolt ikan ada serbuknya). Tidak perlu khawatir, karena itu adalah bumbu makanan bolt nya, bukan karena hancur ya kaka2. Itu diperlukan utk menambah nafsu makan kucing kesayangan kk<br>- Kalau ragu timbangannya, PASTIKAN menimbang dengan TIMBANGAN DIGITAL ya kk, bukan timbangan perasaan. Kita menggunakan timbangan digital merk CMOS dengan ketelitian 2 angka desinal di belakang koma, jadi PASTI PAS 👍NETTO 900Gr ya kk<br>(Timbangan menggunakan timbangan digital yg punya sertifikat uji dari badan metrologi Indonesia. Biasa digunakan di Alfa/indomaret dan ekspedisi2 indonesia seperti JNT)<br><br>Ada 2 kemasan, di kirim Random ☺️<br>1. Plastik Bolt<br>2. Plastik Zipper Lock<br>Dengan kemasan zipper lock tebal dan praktis, menjaga kualitas makanan si empuss supaya tetap fresh<br><br>Makanan kering repack merk bolt<br>NETTO: 900gr<br>Bentuk: Ikan<br>Rasa: Tuna<br><br>- Semua produk yang kita jual adalah Original langsung dari pabriknya<br>- Untuk bolt donat, biasanya serbuknya (tidak menutupi kemungkinan juga bolt ikan ada serbuknya). Tidak perlu khawatir, karena itu adalah bumbu makanan bolt nya, bukan karena hancur ya kaka2. Itu diperlukan utk menambah nafsu makan kucing kesayangan kk<br>- Kalau ragu timbangannya, PASTIKAN menimbang dengan TIMBANGAN DIGITAL ya kk, bukan timbangan perasaan. Kita menggunakan timbangan digital merk CMOS dengan ketelitian 2 angka desinal di belakang koma, jadi PASTI PAS 👍<br><br>Bolt diformulasikan untuk memenuhi nutrisi standar Profil Nutrisi Makanan Kucing yang disahkan oleh AAFCO (Association of American Feed Control Officials).<br><br>Expired panjang (Message untuk cek expired)<br><br>- Highly digestible<br>- For Healthy skin & coat<br>- Appealing flavor<br><br>Guaranteed Analysis:<br>Crude Protein: Min 28%<br>Crude Fat: Min 9%<br>Crude Fiber: Max 4%<br>Moisture: Max 10%<br><br><br>WAJIB DIBACA:<br>RULES GOJEK/GRAB<br>- SAMEDAY, orderan masuk sblm pkl 11:00 dikirim hari yg sama. Yg pengen buru2 DILARANG pakai sameday ya<br>- INSTANT, orderan masuk sblm pkl 15:00 dikirim hari yg sama<br><br>RULES JNT/JNE<br>- Pembayaran sblm 11:00wib dikirim di hari yg sama<br>- WAJIB Bubble/kotak utk produk2 mudah pecah. Kerusakan di expedisi bukan tggjwb kami ', 'Food'),
(9, 'Cat Choize - 800gr', 17999, 'Makanan Kucing kering murah Cat Choize TUNA ADULT 800gr<br><br>CAT CHOIZE mengandung nutrisi , vitamin dan mineral lengkap yang menjaga kesehatan kucing. Diet yang seimbang telah dikembangkan untuk memastikan pertumbuhan kucing yang optimal.<br>CAT CHOIZE cocok untuk semua ras dan tahap kehidupan kucing<br><br>KESEHATAN GIGI :<br>Tektur Kibble yang renyah membantu mengurangi penumpukan wabah dan memutihkan gigi<br><br>FUNGSI PENCERNAAN :<br>serat yang dipilih membantu mendukung fungsi percernaan yang optimal<br><br>Kulit dan Bulu yang sehat : asam lemak omega 6 dan seng menghasilkan kulit dan bulu yang sehat', 'Food'),
(10, 'Cat Choize Kitten', 24500, 'MAKANAN KUCING CAT CHOIZE KITTEN 1 Kg - Tuna Kitten & Salmon Kitten<br><br>Cat choize kitten diformulasikan untuk memenuhi kebutuhan nutrisi anak kucing.<br>Mengandung nutrisi lengkap, vitamin dan mineral yang membantu memperkuat sistem kekebalan tubuh, serta mendukung pertumbuhan dan perkembangan yang tepat pada anak kucing pada masa pertumbuhanny dan cocok untuk semua jenis kucing.<br><br>Komposisi :<br>sereal gandum, tepung gluten jagung, tepung kedelai, minyak (ayam/kelapa sawit olahan), gandum dan atau beras, kedelai lemak penuh, mineral, tuna olahan, hidrolisat ayam, susu skim, vitamin, minyak ikan, DL-methionine (asam amino), potassium sorbate, Taurine dan antioksidan.<br><br>HIGH QUALITY PROTEIN<br>Sumber protein berkualitas dari ikan tuna asli, susu dan ayam membantu meningkatkan pertumbuhan otot dan perkembangan pada anak kucing.<br><br>HEALTHY IMMUNE SYSTEM<br>Selenium dan vitamin E membantu meningkatkan fungsi kekebalan tubuh anak kucing anda.<br><br>STRONG BONES AND TEETH<br>Kalsium, fosfor dan vitamin D membantu memperkuat tulang dan gigi.<br><br>HIGH PALATABILITY FOR KITTEN<br>Terbuat dari bahan-bahan berkualitas, anak kucing akan menikmati kelezatannya makanan sehari-harinya.<br><br>Analisis Nutrisi :<br><br>Crude Protein min 30.0%<br>Crude Fat min 9.0%<br>Crude Fiber max 4.0%<br>Moisture max 10.0%', 'Food'),
(11, 'Cat Sand', 7500, 'NEW PACKAGING<br>KEMASAN PLASTIK ZIPPER LOCK<br><br>Pasir kucing Cub n Kit 1 kg<br>Kualitas terbaik<br>Original<br><br>Aroma Acak ya kaka tergantuk stok repack yg ready, random salah 1 dari 4 varian ini (tidak bisa pilih aroma untuk kemasan repack)<br>- Coffee<br>- Lavender<br>- Lemon<br>- Apple<br><br>Limited stock!<br><br>NB: kami jual harga grosir eceran langsung sudah Net, semua pengiriman hanya menggunakan bungkus plastik saja,<br>Apabila ingin lebih safety (dijual terpisah) bisa order tambahan di iklan dus / bubblewrap / plastik tambahan', 'Toy / Utility'),
(12, 'Catnip Powder', 12500, 'anggal Produksi ada di sebelah kanan atas Packaging<br>EXP : 2 tahun dr masa produksi nya<br><br>Catnip adalah satu hal yang dapat membuat kucingmu sangat gembira. Hal ini membuat mendorong mereka untuk bermain, berlatih dan senang. Tapi mengapa Catnip sangat menarik bagi kucingmu, dan bagaimana caramu menggunakannya agar si kecil bahagia?<br><br><br>Apa itu catnip?<br><br>Catnip – atau yang disebut juga catmint – adalah tanaman herbal dari keluarga mint. Orang – orang telah menggunakan catnip sebagai obat untuk menyembuhkan berbagai macam keluhan sejak zaman Romawi kuno. Sekarang, tanaman ini juga digunakan sebagai teh herbal untuk membantu pencernaan. Untuk para kucing – mereka tidak akan pernah puas!<br><br><br>Apakah semua kucing beraksi terhadap catnip?<br><br>Tidak – tidak semua kucing peka akan catnip. Namun, mayoritas kucing akan sangat senang ketika menemukannya. Dan beberapa singa/harimau juga diketahui sangat menyukai catnip<br><br><br>Berapa lama efek catnip berlangsung?<br><br>Kehebohan kucing anda akan catnip biasanya hanya bertahan beberapa menit. Setelah itu, dia akan terbiasa dengan kimia yang terdapat di dalamnya yang memicu reaksinya itu. Sekitar satu atau beberapa jam kemudian kebiasaan itu akan hilang, dan dia akan kembali heboh dengan catnip lagi!<br><br><br>Apakah catnip benar – benar aman?<br><br>Catnip bersifat non-adiktif, di mana kamu dapat meyakinkan dirimu bahwa jika kucingmu mengigit daunnya, itu tidak akan melukainya sama sekali. Bahkan kamu dapat membeli mainan, kudapan dan selimut yang direndam atau dibumbui dengan catnip.<br><br><br>FUNGSI CATNIP:<br><br>1.Membuat Kucing Merasa Fly<br>2. Membuat Kucing Bahagia tanpa Rasa Sakit di Kemudian Hari (Tanpa Efek Samping)<br>3. Menyembuhkan Beragam Penyakit pada Kucing<br>4. Memberi Efek Halusinogen<br>5. Membuat Kucing Rileks dan Santai<br>6. Baik untuk Kucing yang Malas Bergerak<br>7. Membuat Kucing Ceria<br>8. Membuat Kucing Bersemangat<br>9.Dapat Menyembuhkan Scabies (caranya: Tumbuk halus catnip dan oleskan pada bagian kulit', 'Toy / Utility'),
(13, 'Catnip Stick', 12000, 'CATNIP stick snack kucing untuk kesehatan & gigi<br><br>TERSEDIA 2 VARIASI PILIHAN :<br>- Catnip 5gr (4-5 batang, tergantung besar batangnya)<br>- Catnip 10gr (8-10 batang, tergantung besar batangnya)<br><br>Berat per pack adalah 5gr / 10gr netto, dgn ukuran batang yg berbeda (ad batangan yg tebal & tipis)<br>Catnip adalah tanaman aromatic yang sangat disukai oleh kucing, aromanya akan membuat kucing relaks, tenang & bahagia.<br><br>catnip juga bisa membersihkan gigi kucing supaya tidak ada plak', 'Toy / Utility'),
(14, 'Cats Talcum powder', 25000, 'Bedak Tabur Kucing / Cats Talcum Power Anti Kutu Dan Jamur Netto 100 Gram<br><br>Cara Pemakaian: Taburkan Bedak pada bulu kucing Anda, Usap dan bersihkan tanpa dibilas.<br><br>Cat Taum Powder merupakan bedak untuk hewan peliharaan Anda.<br><br>Bedak ini diformulasikan untuk semua jenis kucing.<br>Taum Powder ini juga mengandung triclosan sebagai anti bakteri dan jamur, iritasi serta dengan Zink Oxide sebagai anti ketombe.<br><br>Kegunaan:<br><br>1. KUNING | Cat Taum Powder Tick & Fleas<br>Memiliki keharuman pappermint Oil yang dilengkapi dengan sulfur, salicylic acid sebagai anti jamur dan iritasi. Bedak ini juga dilengkapi dngan Cabaryl sebagai anti kutu, caplak dan pinjal dengan kadar yang aman sesuai rekomendasi dokter hewan.<br><br>2. Oren | Medicated taum powder<br>Mengandung salicylic acid, sulfur yang akan mengatasi masalah kulit : ich, jamur, dermatitis, gatal-gatal, iritasi kulit<br><br>3. Ungu | Fragrance Swety fruit<br>Bedak ini bisa menyerap keringat sehingga bulu tidak menggumpal dan tetap kering dan wangi. Semua bedak mengandung bahan yang aman untuk hewan, triclosan sebagai anti bakteri, anti jamur, anti iritasi, zink oxide sebagai anti ketombe.', 'Healthcare'),
(15, 'Contra Flu', 16200, 'CONTRA FLU CAT<br>10 ML<br>UNTUK KUCING DEWASA<br><br><br>INDIKASI<br>- MENGOBATI INFEKSI SALURAN PERNAFASAN<br>- BATUK & PILEK / FLU<br><br>KOMPOSISI<br>TIAP MILI MENGANDUNG<br>- TYLOSINE 40 mg<br>- ANTALGIN 25 mg<br>- DYPENHYDRAMINE 1 mg<br><br>CARA PAKAI :<br>- TETESKAN LANGSUNG KE MULUT 2 X SEHARI ( PAGI & SORE)<br>Peroral<br><br>DOSIS<br>0,25 -0.5ml untuk 1 kg BERAT BADAN<br><br>0.25ml = 1 tetes<br>0.5ml = 2 tetes per 1 KG berat badan<br><br>DI FORMULASIKAN OLEH<br>DRH M. BURHAN<br>BY MEYER<br><br>NFG: D. 14.02.2020.01PO.001<br>MENTAN RI NO 2868KSR140.8.2010', 'Healthcare'),
(16, 'Equibrilio', 69000, 'Makanan Kucing Equilibrio<br><br>All Breed untuk Semua Jenis kucing, merupakan rekomedasi terbaru makanan kucing terbaik dari para cat lovers, Equilibrio Kitten ( untuk usia dibawah 12 bulan), diperkaya oleh32 protein tinggi untuk memenuhi kebutuhan kitten, agar tubuh kucing lebih sehat dan dapat memicu keaktifan diusia kucing kecil.<br><br>Komposisi Produk :<br><br>Jagung tanah kuning, Ayam deboned, tepung ikan, bir beras, gluten tepung jagung, ragi bir kering, hati unggas, ground flaxseed, lemak unggas (diawetkan dengan tokoferol campuran alam dan minyak rosemary), minyak ikan, beet pulp, inulin, dikalsium fosfat , klorida kolin, DL-metionin, asam fosfat, kalium klorida, ekstrak yucca Schidigera, natrium hexametaphosphate, vitamin premix dan premix mineral chelate<br><br>Cara mengganti pakan kucing anda ke pakan Equilibrio Excelencia em Nutricao. Berikan makanan lama dengan pada hari pertama dengan perbandingan 25 persen Equilibrio 75 persen produk lama hingga 3 hari. Hari ke empat hingga hari ke enam perbandingan 50 persen produk lama dan 50 persen equilibrio. Hari ke sembilan hingga ke 12 25 persen produk lama dan 75 persen produk baru, hari ke 12 hingga seterusnya bisa pakai produk baru. berlaku untuk penggantian pakan apapun. *Rekomendasi dari Dokter Hewan', 'Food'),
(17, 'Fleas Collar', 8000, 'Kalung Kucing Bebas Kutu Anti Kutu Aman dan Ampuh Menghilangkan Kutu Dari Hewan Kesayangan<br><br>Ukuran 1,5 x 40 cm<br>Warna: Merah', 'Healthcare'),
(18, 'Lifecat Pouch', 4999, 'Premium Cat food untuk kucing dengan komposisi yang terdiri dari ayam & ikan yang mengandung banyak vitamin & mineral seperti vitamin B12 , Vit D Vit A, Vit E dan masih banyak lagi bahan yang sangat bermanfaat untuk kucing kesayangan anda. (komposisi lengkap di kemasan)<br><br>Kelebihan :<br>- Baik untuk pencernaan kucing<br>- Meningkatkan daya tahan tubuh<br>- Menyehatkan pertumbuhan otot-otot kucing<br>- Menyehatkan kulit kucing dan meningkatkan kekebalan tubuh kucing', 'Food'),
(19, 'Litter box L', 15000, NULL, 'Toy / Utility'),
(20, 'Me-O Creamy', 19900, 'Merupakan cemilan sekaligus vitamin penambah nafsu makan kucing kesayanganmu.<br>Terdiri dari kandungan vitamin dan mineral yg diperlukan kucing<br>Ukuran 15 ml per sachet<br>Harga yang tertera merupakan Harga per pack Isi 4 sachet', 'Food'),
(21, 'Me-O Original', 45500, 'MEO PERSIAN ADULT 1 KG<br><br>* Direkomendasikan untuk kucing jenis bulu panjang (longhar) seperti persia.<br><br>Kemasan Re-pack 1 KG Plastik ziplock food grade, menjaga kualitas makanan supaya tetap fresh.<br><br>+ Kandungan vitamin dan mineral untuk mencegah kerontokon bulu.<br>+ Mengandung asam amino omega 3 dan omega 6 untuk merangsang kilauan dan kehalusan pada bulu kucing.<br>+ Asam amino penting seperti Taurine untuk ketajaman penglihatan.<br>+ Mengandung fiber alami untuk kesehatan sistem pencernaan yang membantu mengeluarkan hairball melalui feses<br>+ Mengurangi resiko penyakit saluran kencing FLUTD (Feline Lower Urinary Tract Disease).<br><br>Bahan-Bahan :<br>Corn, Poultry by-product meal, Stabilized animal fats, Corn gluten meal, Soybean meal, Fish meal, Vegetable fiber, Beet pulp, Stabilized Fish Oil, Flax Seed, Lecithin, Palatans, DL methionine, Taurine, Antioxidant, Choline chloride, Vitamins (Vit A, Vit D, Nicotinic acid, Vit E, Vit B1, Pantohenic acid, Vit B2, Vit B6, Folic acid, Vit K, Biotin, Vit B12), Mineral (Monocalcium phosphate, Pottasium chloride, Sodium chloride, Ferrous sulfate, Zinc, Copper sulfate, Manganous oxide, Potassium iodide, Sodium selenite.<br><br>Komposisi:<br>Protein (min.30%); Lemak (min.15%); Serat (max.9%); Abu (max.10%)<br><br>#makanankucingpersia #meopersianadult #meopersian', 'Food'),
(22, 'Me-O Salmon', 38500, 'REPACK PRODUK menggunakan plastik ZIPLOCK<br>tersedia 2 rasa : Salmon & Tuna<br><br>Fitur Me-O Cat Food:<br><br>Taurin adalah asam amino essensial yang diperlukan untuk kesehatan mata dan ketajaman penglihatan kucing.<br>Vitamin C meningkatkan sistem imunitas dan membantu mengatasi stress terhadap lingkungan.<br>Kalsium, Fosfor dan Vitamin D membantu memperkuat gigi dan tulang.<br>Diformulasikan dengan mineral & vitamin yang seimbang untuk mencegah resiko penyakit pada saluran kencing / FLUTD ( Feline Lower Urinary Tract Disease ) dan batu kandung kemih.<br>Omega-3 dan Omega-6 dari minyak berkualitas tinggi dikombinasikan dengan Seng (Zn), untuk memelihara kesehatan rambut dan kulit serta memelihara kerja sistem syaraf.<br>Formula sodium menurunkan resiko terhadap tekanan darah tinggi, ginjal dan penyakit jantung pada kucing.<br><br>Bahan-Bahan:<br>Ground corn, chicken by product meal, soybean meal, corn glutten meal, fish meal, tuna by product meal, chicken fat, brewers dried yeast, iodized salt, fish digest, taurine, vitamins and minerals, antioxidant and food coloring.<br><br>Protein Min 30%<br>Fat Min 9%<br>Serat Max 4%<br>Kadar Air Max 10%', 'Food'),
(23, 'Miconazole', 48500, 'Miconazole Shampoo 200ml<br><br>Shampoo obat rekomendasi para dokter hewan<br>- Membasmi kutu dan jamur<br>- Mengurangi ketombe<br>- Untuk kucing dan anjing<br><br>-ATURAN PEMAKAIAN<br>😺 Basuh kucing atau anjing dengan air hangat hingga basah seluruh badan<br>😺 Ambil shampo secukupnya balurkan ke tubuh anjing atau kucing merata.<br>😺 Gosok bagian yang berkutu atau berjamur lebih lama. Diamkan 5-7 menit. lalu bilas kembali dengan air hangat.<br>😺 Gunakan secara rutin satu minggu 1x selama treatment untuk menghilangkan kutu dan jamur<br>😺 Setelah itu shampo tetap bisa digunakan meski kutu dan jamur sudah hilang, sebagai shampo biasa. Mandikan kucing atau anjing seperlunya saja atau ketika kotor<br>😺 Keringkan kucing dan anjing yang sudah dimandikan sampai benar-benar kering, dan jemur di bawah matahari.<br>😺 Mandikan kucing di pagi hari', 'Healthcare'),
(24, 'Pet Bed', 60000, 'PET BED kasur tempat tidur kucing tersedia 2 motif pilihan<br>- motif jerapah<br>- motif leopard<br><br>PERHATIAN ! sebelum membeli, mohon cek dahulu ukurannya apa sudah sesuai atau belum ya kk 🙏🏻 ukuran panjang kurang lebih 40cm x 32cm yah (Ukuran SMALL/kecil). Cocok utk kucing ukuran sedang, kalau anjing besar tdk muat ya ka.. karena kami tidak menerima kalau refund kekecilan / tidak sesuai ya 🙏🏻<br><br>● Kain Bantal Terbuat Dari Kain Karfur Halus,Lembut.<br>● Kain Kasur Terbuat Dari Kain Printing Kualitas Premium GRADE A.<br>● Ukuran Keseluruhan Panjang 40cm dan Lebar 32cm (Kurang Lebih)<br>● Bahan Sangat Halus dan Lembut.<br>● Bantal dan Kasur Diisi Kapas Silikon GRADE A (Kualitas Sangat Empuk)<br>● Alas Bisa Dilepas agar memudahkan saat dicuci.<br>● Sangat Cocok untuk ukuran Kucing Sedang atau Anjing Kecil.', 'Toy / Utility'),
(25, 'Pet Brush', 16000, 'Sisir Sikat Slicker Bulu Rambut Anjing Kucing Pet Brush Comb Grooming<br><br>Slicker brush / sisir slicker untuk mengangkat bulu mati hewan peliharaan.<br>Menjadikannya bulu hewan peliharaan Anda lebih halus dan mengembang.<br><br>Bahan badan sikat : plastic<br>Ukuran kepala sikat : 10 x 5.5 cm<br>Panjang 13.5 cm', 'Toy / Utility'),
(26, 'Pet Toothbrush', 4500, 'Hai Pet Lovers , kalian suka bingung ga sih apa kucing/anjing perlu sikat gigi?<br>Perlu loh teman - teman , karena setiap dia makan ada saja makanan yang tertinggal di gigi mereka , dan sisa - sisa makanan tersebut akan menjadi tempat bersarangnya bakteri loh !<br>Dan parahnya lagi bisa menyebabkan gigi berlubang , radang gusi.<br><br>Bahan sikat gigi ini sangat aman dan lembut loh , jadi jangan khawatir lecet ya.<br>Untuk keterangan size bisa kalian cek difoto ya', 'Toy / Utility'),
(27, 'Pipet - 1ml', 1800, 'JARUM BISA DI CABUT 1ML dan 3ML<br>Spuit Spet Suntikan 1 cc ml dan 3 cc ml<br>digunakan untuk menyuntikan obat secara IM / IV / CS / ID dan untuk mengambil cairan / darah hewan<br>dapat dipergunakan juga media pemberian susu / obat / vitamin ke bayi hewan kecil<br>KEUNGGULAN<br>- Disposible<br>- Sterile with ethylene oxide<br>- nontoxic<br>- non Pyrogenic<br>- luer lock tip', 'Toy / Utility'),
(28, 'POPI Shampoo', 38000, 'POPI SHAMPOO ANTI FUNGAL TICK & FLEA 250ml (For Cat & Dog)<br><br>WATER BASED SHAMPOO! Shampo ini CAIR, agar gampang dibilas sehingga TIDAK menyisakan sisa shampo di kulit. Karena kutu & jamur bisa kembali jika masih ada sisa shamponya!<br><br>100% AMAN karena tidak mengandung sulfat & soda api. sehingga aman untuk hewan peliharaan. Dengan aromaterapi lavender oil yg menyehatkan & wangi yg tahan lama.<br><br>Dilengkapi dengan Kandungan minyak atsiri yang melembutkan & menutrisi bulu<br><br><br>- KETERANGAN PRODUK<br>😺 shampo anti kutu bagi Kucing dan Anjing dengan berat isi 250ml<br>😺 Dengan formula pewangi yang lembut dan tahan lama<br>😺 Mampu menyembuhkan jamur ringan<br>😺 Membunuh telur kutu<br>😺 Memotong lingkaran hidup kutu dan menjaga kulit<br>😺 Membersihkan dan melembutkan bulu<br>😺 Mensterilkan kulit dan bulu<br>😺 Bisa dipakai untuk KUCING maupun ANJING<br>😺 Terbuat dari bahan-bahan yang sudah teruji aman dan berkualitas dengan aroma alami yang menyegarkan bagi hewan peliharaan anda<br><br>-ATURAN PEMAKAIAN<br>😺 Basuh kucing atau anjing dengan air hangat hingga basah seluruh badan<br>😺 Ambil sekitar 10-30ml shampo dan balurkan ke tubuh anjing atau kucing merata.<br>😺 Gosok bagian yang berkutu atau berjamur lebih lama. Diamkan 5-7 menit. lalu bilas kembali dengan air hangat.<br>😺 Gunakan secara rutin satu minggu 1x selama treatment untuk menghilangkan kutu dan jamur<br>😺 Setelah itu shampo tetap bisa digunakan meski kutu dan jamur sudah hilang, sebagai shampo biasa. Mandikan kucing atau anjing seperlunya saja atau ketika kotor<br>😺 Keringkan kucing dan anjing yang sudah dimandikan sampai benar-benar kering, dan jemur di bawah matahari.<br>😺 Mandikan kucing di pagi hari', 'Healthcare'),
(29, 'POPI-DOT Pet Nipple', 24000, 'Material : Food-grade silicone,<br>cocok untuk: Bayi kucing ,anjing, kelinci dan bayi hewan lainnya<br><br>Fitur:<br>1. Dot tidak mudah copot<br>2. Material yg aman, menggunakan food-grade silicone, dapat disterilkan beberapa kali<br>3. Kenyal & nyaman di mulut pets<br>4. Dot digunakan bersamaan dgn spuit<br>5. Mudah & praktis penggunaannya<br><br>Spesifikasi:<br>Kondisi: 100% baru<br><br>Diameter dot: 2 cm', 'Toy / Utility'),
(30, 'True Touch', 25000, 'Real Smart Pet Glove True Touch<br><br>Sarung Tangan Pemijat Perapi Bulu Hewan Anjing Kucing<br><br>Mengangkat bulu bulu mati yang ada di tubuh hewan kesayangan anda.<br><br>Sehingga menjadikannya lebih sehat.<br><br>Sehat untuk hewan peliharaan anda dan sehat untuk keluarga dirumah.<br><br>MERK : TRUETOUCH<br>ORIGINAL<br>(PAKAI DUS)<br><br>STOK YG READY TANGAN KANAN', 'Toy / Utility'),
(31, 'Whiskas Pouch', 6500, 'Makanan Kucing Whiskas Sachet 85 gram all varian. dengan berbagai pilihan rasa yang tidak bisa di tolak oleh kucing kesayangan anda. Terbuat dari berbagai kandungan rasa yang memenuhi nutrisi untuk kucing kesayangan anda. Whiskas sachet 85 gram sangat cocok untuk segala jenis kucing kesayangan anda.', 'Food'),
(32, 'Wormcetin', 8000, 'INDIKASI :<br>- MENGOBATI PENYAKIT YG DI SEBABKAN OLEH PARASIT LUAR (KUTU, CAPLAK, TUNGAU DAN INSEKTA LAINNYA)<br>- MENGOBATI PENYAKIT CACING<br><br>ATUTAN PAKAI<br>OBAT DI SUNTIKAN DI BAWAH KULIT<br>- SAPI 1ML TIAP 50 KG BERAT BADAN PER HARI<br>- BABI 1ML TIAP 33 KG BERAT BADAN PER HARI<br>- DOMBA 0.5ML TIAP 25KG BERAT BADAN PER HARI<br>- ANJING, KUCING : 0.02 ML KG BERAT BADAN PER HARI<br><br>##suntikan 3 sampai 7 hari lihat keadaan hewan<br><br>* PERHATIAN<br>- JANGAN DIBERIKAN PADA ANJING RAS COLLIE<br>- HENTIKAN PEMAKAIAN OBAT 28 HARI SEBELUM TERNAK DIPOTONG UNTUK KOMSUMSI<br>- SIMPAN OBAT DI TEMPAT YG KERING DAN TERTUTUP RAPAT, TERHIDAR DAN SINAR MATAHARI LANGSUNG', 'Healthcare');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `product`
--
ALTER TABLE `product`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
